version: '3.7'

services:
  reviewboard:
    image: beanbag/reviewboard:4.0
    depends_on:
      - db
      - memcached
    environment:
      - COMPANY=CTI Software Development
      - DATABASE_TYPE=mysql
      - DATABASE_SERVER=db
      - DATABASE_NAME=reviewboard
      - DATABASE_USERNAME=reviewboard
      - DATABASE_PASSWORD=reviewboard123
      - DOMAIN=cti-rum-upr.reviews.com
      # Enable search indexing and user session cleanup
      # - REVIEWBOARD_CRONTAB=/site/conf/cron.conf
    ports:
      - "8000:8080"
    volumes:
      - sitedir:/site

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - reviewboard
    environment:
      - NGINX_HOST=cti-rum-upr.reviews.com
      - NGINX_PORT=80
    ports:
      - 80:80
    volumes:
      - sitedir:/var/www/reviewboard
      - ./nginx_templates:/etc/nginx/templates

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=reviewboard
      - MYSQL_USER=reviewboard
      - MYSQL_PASSWORD=reviewboard123
    volumes:
      - db_data:/var/lib/mysql
    restart: 'on-failure'

  memcached:
    image: memcached:alpine
    restart: 'on-failure'

networks:
  default:
    external:
      name: techrum_pipeline_network
volumes:
  db_data:
  sitedir:
